
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftANDleftEQNELTGTLEGEAND AS CALL COMMA CREATE DISCARD DO END EQ EXPORT FROM GE GT ID IMPORT JOIN LE LIMIT LPAREN LT NE NUMBER PRINT PROCEDURE RENAME RPAREN SELECT SEMICOLON STAR STRING TABLE USING WHEREprogram : command_listcommand_list : command SEMICOLON\n                       | command SEMICOLON command_listcommand : import_cmd\n                  | export_cmd\n                  | discard_cmd\n                  | rename_cmd\n                  | print_cmd\n                  | select_cmd\n                  | create_cmd\n                  | procedure_def\n                  | procedure_callimport_cmd : IMPORT TABLE ID FROM STRINGexport_cmd : EXPORT TABLE ID AS STRINGdiscard_cmd : DISCARD TABLE IDrename_cmd : RENAME TABLE ID IDprint_cmd : PRINT TABLE IDselect_cmd : SELECT select_list FROM TABLE IDselect_list : STAR\n                   | IDcreate_cmd : CREATE TABLE IDprocedure_def : PROCEDURE ID DO command_list ENDprocedure_call : CALL ID'
    
_lr_action_items = {'IMPORT':([0,22,42,],[13,13,13,]),'EXPORT':([0,22,42,],[14,14,14,]),'DISCARD':([0,22,42,],[15,15,15,]),'RENAME':([0,22,42,],[16,16,16,]),'PRINT':([0,22,42,],[17,17,17,]),'SELECT':([0,22,42,],[18,18,18,]),'CREATE':([0,22,42,],[19,19,19,]),'PROCEDURE':([0,22,42,],[20,20,20,]),'CALL':([0,22,42,],[21,21,21,]),'$end':([1,2,22,34,],[0,-1,-2,-3,]),'SEMICOLON':([3,4,5,6,7,8,9,10,11,12,33,37,39,41,45,48,49,50,51,],[22,-4,-5,-6,-7,-8,-9,-10,-11,-12,-23,-15,-17,-21,-16,-13,-14,-18,-22,]),'TABLE':([13,14,15,16,17,19,40,],[23,24,25,26,27,31,46,]),'STAR':([18,],[30,]),'ID':([18,20,21,23,24,25,26,27,31,38,46,],[29,32,33,35,36,37,38,39,41,45,50,]),'END':([22,34,47,],[-2,-3,51,]),'FROM':([28,29,30,35,],[40,-20,-19,43,]),'DO':([32,],[42,]),'AS':([36,],[44,]),'STRING':([43,44,],[48,49,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'command_list':([0,22,42,],[2,34,47,]),'command':([0,22,42,],[3,3,3,]),'import_cmd':([0,22,42,],[4,4,4,]),'export_cmd':([0,22,42,],[5,5,5,]),'discard_cmd':([0,22,42,],[6,6,6,]),'rename_cmd':([0,22,42,],[7,7,7,]),'print_cmd':([0,22,42,],[8,8,8,]),'select_cmd':([0,22,42,],[9,9,9,]),'create_cmd':([0,22,42,],[10,10,10,]),'procedure_def':([0,22,42,],[11,11,11,]),'procedure_call':([0,22,42,],[12,12,12,]),'select_list':([18,],[28,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> command_list','program',1,'p_program','parser.py',24),
  ('command_list -> command SEMICOLON','command_list',2,'p_command_list','parser.py',28),
  ('command_list -> command SEMICOLON command_list','command_list',3,'p_command_list','parser.py',29),
  ('command -> import_cmd','command',1,'p_command','parser.py',36),
  ('command -> export_cmd','command',1,'p_command','parser.py',37),
  ('command -> discard_cmd','command',1,'p_command','parser.py',38),
  ('command -> rename_cmd','command',1,'p_command','parser.py',39),
  ('command -> print_cmd','command',1,'p_command','parser.py',40),
  ('command -> select_cmd','command',1,'p_command','parser.py',41),
  ('command -> create_cmd','command',1,'p_command','parser.py',42),
  ('command -> procedure_def','command',1,'p_command','parser.py',43),
  ('command -> procedure_call','command',1,'p_command','parser.py',44),
  ('import_cmd -> IMPORT TABLE ID FROM STRING','import_cmd',5,'p_import_cmd','parser.py',49),
  ('export_cmd -> EXPORT TABLE ID AS STRING','export_cmd',5,'p_export_cmd','parser.py',53),
  ('discard_cmd -> DISCARD TABLE ID','discard_cmd',3,'p_discard_cmd','parser.py',66),
  ('rename_cmd -> RENAME TABLE ID ID','rename_cmd',4,'p_rename_cmd','parser.py',70),
  ('print_cmd -> PRINT TABLE ID','print_cmd',3,'p_print_cmd','parser.py',74),
  ('select_cmd -> SELECT select_list FROM TABLE ID','select_cmd',5,'p_select_cmd','parser.py',78),
  ('select_list -> STAR','select_list',1,'p_select_list','parser.py',82),
  ('select_list -> ID','select_list',1,'p_select_list','parser.py',83),
  ('create_cmd -> CREATE TABLE ID','create_cmd',3,'p_create_cmd','parser.py',87),
  ('procedure_def -> PROCEDURE ID DO command_list END','procedure_def',5,'p_procedure_def','parser.py',91),
  ('procedure_call -> CALL ID','procedure_call',2,'p_procedure_call','parser.py',95),
]
